Try fighting the weird CoCalc error
Kevin says CoCalc says:
TypeError: missing_host_key() missing 1 required positional argument: 'key'
when trying to connect using ssh, and then
https://stackoverflow.com/questions/36237172/paramiko-error-missing-host-key-missing-1-required-positional-argument-key
suggests this modification.